// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Task struct {
	ID        int32
	TaskName  string
	StartTime time.Time
	EndTime   sql.NullTime
}
