// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const completedTasks = `-- name: CompletedTasks :many
SELECT id, task_name, start_time, end_time FROM tasks WHERE end_time IS NOT NULL ORDER BY id
`

func (q *Queries) CompletedTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, completedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNewTask = `-- name: CreateNewTask :one
INSERT INTO tasks (task_name, start_time) VALUES ($1, $2) RETURNING id, task_name, start_time, end_time
`

type CreateNewTaskParams struct {
	TaskName  string
	StartTime time.Time
}

func (q *Queries) CreateNewTask(ctx context.Context, arg CreateNewTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createNewTask, arg.TaskName, arg.StartTime)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const runningTasks = `-- name: RunningTasks :many
SELECT id, task_name, start_time, end_time FROM tasks WHERE end_time IS NULL ORDER BY id
`

func (q *Queries) RunningTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, runningTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showSpecificTimer = `-- name: ShowSpecificTimer :one
SELECT id, task_name, start_time, end_time FROM tasks WHERE id = $1
`

func (q *Queries) ShowSpecificTimer(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, showSpecificTimer, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const truncateTasks = `-- name: TruncateTasks :exec
TRUNCATE TABLE tasks RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateTasks)
	return err
}

const updateSelectedTask = `-- name: UpdateSelectedTask :one
UPDATE tasks SET end_time = $1 WHERE id = $2 AND end_time IS null RETURNING id, task_name, start_time, end_time
`

type UpdateSelectedTaskParams struct {
	EndTime sql.NullTime
	ID      int32
}

func (q *Queries) UpdateSelectedTask(ctx context.Context, arg UpdateSelectedTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateSelectedTask, arg.EndTime, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
