-- +goose Up

-- Name is the primary human handle for a task. Case-insensitive so that
-- "leetcode practice" and "leetcode practice" are the same task rather than two rows
-- silently splitting the same tracked time. Doubles as the lookup index.
CREATE UNIQUE INDEX tasks_name_lower_key ON tasks (lower(name));

-- Short, permanent, monotonic public identifiers. uuid stays the PK and FK
-- target; seq is purely the handle. Identity sequences never reuse values, so
-- deleting a task never renumbers the others.
ALTER TABLE tasks
	ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE tasks
	ADD CONSTRAINT tasks_seq_key UNIQUE (seq);

ALTER TABLE tasks_sessions
	ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE tasks_sessions
	ADD CONSTRAINT tasks_sessions_seq_key UNIQUE (seq);

-- A recurring task cycles In Progress <-> Paused forever and is retired with
-- Archived, never Completed. Single-row, so a CHECK expresses it exactly.
ALTER TABLE tasks
	ADD CONSTRAINT tasks_recurring_never_completed
	CHECK (NOT (type = 'Recurring' AND status = 'Completed'));

-- Retire the trigger machinery. Pause and complete both set end_time = now(),
-- so a trigger on tasks_sessions cannot tell them apart -- it can only pick one
-- meaning, and 20260816031031 picked 'Completed'. Status transitions are now
-- written explicitly by the application; the database keeps invariants only.
DROP TRIGGER IF EXISTS update_tasks_is_paused ON tasks_sessions;
DROP FUNCTION IF EXISTS update_tasks_status_to_completed();
DROP FUNCTION IF EXISTS update_tasks_status();

-- is_paused is a projection of status, not independent state. Generating it
-- means it can never drift and is not writable.
ALTER TABLE tasks DROP COLUMN is_paused;
ALTER TABLE tasks
	ADD COLUMN is_paused BOOLEAN NOT NULL
		GENERATED ALWAYS AS (status = 'Paused'::tasks_statuses) STORED;

-- Session integrity.
ALTER TABLE tasks_sessions
	ADD CONSTRAINT tasks_sessions_end_after_start
	CHECK (end_time IS NULL OR end_time >= start_time);

-- At most one open session per task. Also the index for open-session lookups.
CREATE UNIQUE INDEX tasks_sessions_one_open_per_task
	ON tasks_sessions (task_id)
	WHERE end_time IS NULL;

-- Session history / SUM aggregation path. task_id was entirely unindexed.
CREATE INDEX tasks_sessions_task_id_start_time_idx
	ON tasks_sessions (task_id, start_time DESC);

CREATE INDEX tasks_status_idx ON tasks (status);

-- Sequence orphaned by the original SERIAL id in 20260812093802.
ALTER SEQUENCE IF EXISTS tasks_id_seq OWNED BY NONE;
DROP SEQUENCE IF EXISTS tasks_id_seq;


-- +goose Down

DROP SEQUENCE IF EXISTS tasks_id_seq;
CREATE SEQUENCE tasks_id_seq;

DROP INDEX IF EXISTS tasks_status_idx;
DROP INDEX IF EXISTS tasks_sessions_task_id_start_time_idx;
DROP INDEX IF EXISTS tasks_sessions_one_open_per_task;

ALTER TABLE tasks_sessions
	DROP CONSTRAINT IF EXISTS tasks_sessions_end_after_start;

ALTER TABLE tasks DROP COLUMN is_paused;
ALTER TABLE tasks ADD COLUMN is_paused BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_recurring_never_completed;

ALTER TABLE tasks_sessions DROP CONSTRAINT IF EXISTS tasks_sessions_seq_key;
ALTER TABLE tasks_sessions DROP COLUMN seq;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_seq_key;
ALTER TABLE tasks DROP COLUMN seq;

DROP INDEX IF EXISTS tasks_name_lower_key;

-- Restore exactly the post-20260816031031 state: both functions present, with
-- update_tasks_is_paused pointing at update_tasks_status_to_completed(), which
-- is what that migration's own Down expects to find.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_tasks_status() RETURNS TRIGGER AS $$
BEGIN
	UPDATE tasks t
	SET is_paused = (n.end_time IS NOT NULL)
	FROM new_task_paused_status n
	WHERE t.id = n.task_id;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql VOLATILE;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_tasks_status_to_completed() RETURNS TRIGGER AS $$
BEGIN
	UPDATE tasks t
	SET status = 'Completed'
	FROM new_task_paused_status n
	WHERE t.id = n.task_id AND n.end_time IS NOT NULL;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql VOLATILE;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE TRIGGER update_tasks_is_paused
	AFTER UPDATE ON tasks_sessions
	REFERENCING OLD TABLE AS old_task_paused_status NEW TABLE AS new_task_paused_status
	FOR EACH STATEMENT
	EXECUTE FUNCTION update_tasks_status_to_completed();
-- +goose StatementEnd
